#!/bin/bash

OCI_NAMESPACE="test_repo" \
  OCI_ROOT_URL="http://127.0.0.1" \
  OCI_CROSSMOUNT_NAMESPACE="public" \
  OCI_USERNAME="harbor_admin" \
  OCI_PASSWORD="admin" \
  OCI_TEST_CONTENT_MANAGEMENT=1 \
  OCI_HIDE_SKIPPED_WORKFLOWS=1 \
  OCI_TEST_PUSH=1 \
  OCI_TEST_CONTENT_DISCOVERY=1 \
  OCI_DEBUG=1 \
  OCI_TEST_PULL=1 \
  OCI_DELETE_MANIFEST_BEFORE_BLOBS=0 \
  ./conformance.test
