services:
  compliance_testing:
    build:
      dockerfile: config/Dockerfile
      context: .
    command: ./conformance.test
    environment:
      OCI_ROOT_URL: http://127.0.0.1:8080
      OCI_NAMESPACE: test_repo
      OCI_USERNAME: floundr_admin
      OCI_PASSWORD: admin
      OCI_TEST_PULL: 1
      OCI_TEST_PUSH: 1
      OCI_TEST_CONTENT_DISCOVERY: 1
      OCI_TEST_CONTENT_MANAGEMENT: 1
      OCI_HIDE_SKIPPED_WORKFLOWS: 0
      OCI_DEBUG: 1
      OCI_DELETE_MANIFEST_BEFORE_BLOBS: 0
      OCI_REPORT_DIR: /report
    network_mode: host
    volumes:
      - logs:/report
    depends_on:
      floundr:
        condition: service_started

volumes:
  data:
  logs:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./logs
