[package]
name = "shared"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = { version = "0.4.38", features = ["serde"] }
serde = { version = "1.0.206", features = ["derive"] }
uuid = { version = "1.10.0", features = ["v4"] }
